_protected/app/controllers/MemberController.php
<?php

namespace app\controllers;

use Yii;
use common\models\Member;
use common\models\MemberImage;
use common\models\MemberSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\Plan;
use common\models\City;
use common\models\Master;
use common\models\State;
use app\models\UploadForm;
use yii\web\UploadedFile;
use yii\db\Expression;
use common\models\Commission;
use yii\helpers\ArrayHelper;
/**
 * MemberController implements the CRUD actions for Member model.
 */
class MemberController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Member models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MemberSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Member model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = Member::find($id)
                        ->with('plan','image','statename','cityname')
                        ->where(['id'=>$id])
                        ->one();
        $team = New Member();   
        $left = $team->getFindLeft($id); 
        $right = $team->getFindRight($id);   
        if(empty($left)){
            $left =0;
        } 
        if(empty($right)){
            $right = 0;
        }         
                       // print_r($model->statename->name);exit;
        //print_r($model);exit;
        return $this->render('view', [
            'model' => $model,
            'left' => $left,
            'right' =>$right,

        ]);
    }

    /**
     * Creates a new Member model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Member();
        $image = new MemberImage();
        $get_member_ddl = $model->getMember();
        $plan = new Plan();
        $get_plan_ddl = $plan->getPlan();
        $state = new State();
        $get_state_ddl = $state->getState();

        if ($model->load(Yii::$app->request->post()) && $image->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
                   // print_r(Yii::$app->request->post());exit;
                $model->dob= date('Y-m-d',strtotime(Yii::$app->request->post('dob')));
                $model->date= date('Y-m-d',strtotime(Yii::$app->request->post('date')));
                
            if ($image->upload_photo = UploadedFile::getInstance($image,'upload_photo')) {
                $image->upload_photo->saveAs(\Yii::getAlias('@webroot') . "/uploads/"  .time() . '.' . $image->upload_photo);
                //save the path in DB..
                $image->upload_photo = $image->upload_photo;
                $image->save();
            }        

            if ($image->id_proof_photo = UploadedFile::getInstance($image,'id_proof_photo')) {
                $image->id_proof_photo->saveAs(\Yii::getAlias('@webroot') . "/uploads/"  .time() . '.' . $image->id_proof_photo);
                //save the path in DB..
                $image->id_proof_photo = $image->id_proof_photo;
                $image->save();
            } 

            if ($image->pan_card_photo = UploadedFile::getInstance($image,'pan_card_photo')) {
                $image->pan_card_photo->saveAs(\Yii::getAlias('@webroot') . "/uploads/"  .time() . '.' . $image->pan_card_photo);
                //save the path in DB..
                $image->pan_card_photo = $image->pan_card_photo;
                $image->save();
            } 
            if ($image->passbook_photo = UploadedFile::getInstance($image,'passbook_photo')) {
                $image->passbook_photo->saveAs(\Yii::getAlias('@webroot') . "/uploads/"  .time() . '.' . $image->passbook_photo);
                //save the path in DB..
                $image->passbook_photo = $image->passbook_photo;
                $image->save();
            }
            $model->created_by =Yii::$app->user->id;
            $model->created_on =  new Expression("now()");
            $model->save();
            //$model->status = '1';
           // $model->save()e;
            $image->member_id = $model->id;
            $image->save();
        /* genarate unique no.*/
            $randomletter = substr(str_shuffle("abcdefghijklmnopqrstuvwxyz"), 0, 5);             
            $model->unique_id = $randomletter.$model->id;
            $model->save();  
        /* update leg count */
            //$ret = explode('/', $model->upline_id);
            //$upline = $ret[0];
         
            $check_sponser = Member::find()
                                    ->where(['id' => $model->sponser_id])
                                    ->One();   
                                    //print_r($check_sponser);exit;       
            if(!empty($check_sponser)){
                if($check_sponser->leg_count ==0){
                    $check_sponser->leg_count=1;
                }
                else{
                    $check_sponser->leg_count=2;
                }
                $check_sponser->save();
                //print_r($check_sponser->errors);exit;
            }
            /* get Direct Commission */
            $to_sponser = $check_sponser->id;
            $from_sponser = $model->id;
            $plan_amount = $model->plan_amount;
            $plan_id = $model->plan_id;
            $commission = new Commission();
            $data = $commission->getDirectCommission($to_sponser,$from_sponser,$plan_amount,$plan_id);
                                 
            $transaction->commit();
            return $this->redirect(['/member']);
            
          // else {
          //    throw new \Exception("Error Saving Invoice :" . json_encode($model->errors), 1);
          //   }
        }
             catch (Exception $exc) {
                $transaction->rollBack();
                throw new \Exception("Error Processing Request " . $exc, 1);
            } 
        }           
        return $this->render('create', [
            'model' => $model,
            'get_member_ddl' => $get_member_ddl,
            'get_plan_ddl' =>$get_plan_ddl,
            'image'=>$image,
            'get_state_ddl' =>$get_state_ddl,
        ]);
    }

    /**
     * Updates an existing Member model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $image = MemberImage::find()
                                    ->where(['member_id' => $id])
                                    ->One();  

                            //print_r($image);exit;
        $get_member_ddl = $model->getMember();
        $plan = new Plan();
        $get_plan_ddl = $plan->getPlan();
        $state = new State();
        $get_state_ddl = $state->getState();   
        $city = new City();

        $get_city_ddl = $city->getCity($model->state);
                     
        if ($model->load(Yii::$app->request->post()) &&  $image->load(Yii::$app->request->post())) {
            

                $model->dob= date('Y-m-d',strtotime(Yii::$app->request->post('dob')));
                $model->date= date('Y-m-d',strtotime(Yii::$app->request->post('date')));
                
            if ($image->upload_photo = UploadedFile::getInstance($image,'upload_photo')) {
                $image->upload_photo->saveAs(\Yii::getAlias('@webroot') . "/uploads/" .$image->upload_photo);
                //save the path in DB..
               $image->upload_photo = $image->upload_photo;
                $image->save();
            }        

            if ($image->id_proof_photo = UploadedFile::getInstance($image,'id_proof_photo')) {
                $image->id_proof_photo->saveAs(\Yii::getAlias('@webroot') . "/uploads/"  .$image->id_proof_photo);
                //save the path in DB..
                $image->id_proof_photo = $image->id_proof_photo;
                $image->save();
            } 

            if ($image->pan_card_photo = UploadedFile::getInstance($image,'pan_card_photo')) {
                $image->pan_card_photo->saveAs(\Yii::getAlias('@webroot') . "/uploads/"  .$image->pan_card_photo);
                //save the path in DB..
                $image->pan_card_photo = $image->pan_card_photo;
                $image->save();
            } 
            if ($image->passbook_photo = UploadedFile::getInstance($image,'passbook_photo')) {
                $image->passbook_photo->saveAs(\Yii::getAlias('@webroot') . "/uploads/"  .$image->passbook_photo);
                //save the path in DB..
                $image->passbook_photo = $image->passbook_photo;
                $image->save();
            }
            $model->updated_by =Yii::$app->user->id;
            $model->updated_on =  new Expression("now()");
            $model->save();
            //$model->status = '1';
           // $model->save()e;
            $image->member_id = $id;
            $image->save();   
            //print_r($image->errors);exit;
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'get_member_ddl' => $get_member_ddl,
            'get_plan_ddl' =>$get_plan_ddl,

_protected/app/views/member/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
use common\models\Master;
/* @var $this yii\web\View */
/* @var $model common\models\Member */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="container">
<div class="member-form">


    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

        <div class="row">    

            <div class="col-md-6">
                  <h5> General Information</h5>
                <?= $form->field($model, 'sponser_id')->dropDownList($get_member_ddl, ['class' => 'select-search', 'prompt' => 'Please Select']) ?>

                <?= $form->field($model, 'upline_id')->textInput(['maxlength' => true,'placeholder' => 'Upline', 'readonly' => true]) ?>
    
                <?= $form->field($model, 'left_right_leg')->dropDownList([ 'left' => 'Left', 'right' => 'Right'], ['prompt' => 'Please Select'])->label('Leg') ?>
          
                <?= $form->field($model, 'applicant_name')->textInput(['maxlength' => true]) ?>
    
                    <?= $form->field($model, 'gender')->dropDownList([ 'male' => 'Male', 'female' => 'Female'], ['prompt' => 'Please Select']) ?>
                <div class="row">
                    <div class="col-md-4">
                        <?= $form->field($model, 'name_type')->dropDownList([ 'S/O' => 'S/O', 'B/O' => 'B/O','W/O' => 'W/O', 'F/O' => 'F/O','D/O' => 'D/O', 'FRM' => 'FRM','COY' => 'COY'], ['prompt' => 'Please Select']) ?>
                    </div>    
                    <div class="col-md-8">
                        <?= $form->field($model, 'father_spouse_name')->textInput(['maxlength' => true]) ?>
                    </div>
                </div> 
            <?= DatePicker::widget([
                        'name' => 'dob', 
                        'value' => date('d-m-Y'),
                        'options' => ['placeholder' => 'Select Date Of Birth ...'],
                        'pluginOptions' => [
                            'format' => 'dd-m-yyyy',
                            'todayHighlight' => true
                        ]
                    ]);?>                   
               
      
                <?= $form->field($model, 'address')->textarea(['rows' => 6]) ?>
                <?= $form->field($model, 'state')->dropDownList($get_state_ddl,
                    [
                        'prompt' => Yii::t('app','Select'),
                        'onchange'=>'
                        $.get( "'.Yii::$app->urlManager->createUrl('member/city-dropdown?id=').'"+$(this).val(), function( data ) {
                        $( "select.city" ).html( data );
                        })'
                    ]); ?>
                <?= $form->field($model, 'city', ['inputOptions'=>['class'=>'city form-control']])->dropDownList(['prompt' => 'Select']) ?>
                <?= $form->field($model, 'mobile')->textInput(['maxlength'=>10]) ?>

                <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
  
                <?= $form->field($model, 'pan_no')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'aadhaar_no')->textInput(['maxlength' => true]) ?>
            </div>              

    <div class="col-md-6">
        <h5> Other Information</h5>
            <?= $form->field($model, 'plan_id')->dropDownList($get_plan_ddl, ['class' => 'select-search', 'prompt' => 'Please Select'])->label('Plan') ?>

            <?= $form->field($model, 'plan_amount')->textInput(['maxlength' => true]) ?>
        <h5> Bank Information</h5>
            <?= $form->field($model, 'bank_name')->textInput(['maxlength' => true]) ?>
 
            <?= $form->field($model, 'account_no')->textInput(['maxlength' => true]) ?>
       
            <?= $form->field($model, 'IFSC_code')->textInput(['maxlength' => true])->label('IFSC Code') ?>

            <?= $form->field($model, 'account_holder_name')->textInput(['maxlength' => true]) ?>
            <?= DatePicker::widget([
                        'name' => 'date', 
                        'value' => date('d-m-Y'),
                        'options' => ['placeholder' => 'Select Date ...'],
                        'pluginOptions' => [
                            'format' => 'dd-m-yyyy',
                            'todayHighlight' => true
                        ]
                    ]);?>
            

   
            <?= $form->field($model, 'nomine_name')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'qualification')->textInput() ?>

            <?= $form->field($image, 'upload_photo')->fileInput(['maxlength' => true]) ?>
                <?php  if($image->upload_photo !=''){?>
                    <img src="<?= \Yii::getAlias('@web') . "/uploads/".$image->upload_photo;?>" width="30%;"> 
                <?php }?>   

            <?= $form->field($image, 'id_proof_photo')->fileInput(['maxlength' => true]) ?>
                <?php  if($image->id_proof_photo !=''){?>
                    <img src="<?= \Yii::getAlias('@web') . "/uploads/".$image->id_proof_photo;?>" width="30%;"> 
                <?php }?>   

            <?= $form->field($image, 'pan_card_photo')->fileInput(['maxlength' => true]) ?>
                <?php  if($image->pan_card_photo != ''){?>
                    <img src="<?= \Yii::getAlias('@web') . "/uploads/".$image->pan_card_photo;?>" width="30%;"> 
                <?php }?> 

            <?= $form->field($image, 'passbook_photo')->fileInput(['maxlength' => true]) ?>
                <?php  if($image->passbook_photo != ''){?>
                    <img src="<?= \Yii::getAlias('@web') . "/uploads/".$image->passbook_photo;?>" width="30%;"> 
                <?php }?> 

                <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>
    </div>

   
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>

    </div>
</div>

    <?php ActiveForm::end(); ?>

</div>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
        $(document).ready( function() {
        $sponser_id =  $('#member-sponser_id').val();
                $.ajax({
                                type : 'post',
                                url : "<?= Url::to(['member/city-dropdown']);?>",
                                //dataType:"json",
                                data:{ 'sponser_id':$sponser_id},
                                success:function(data){ 
                                    alert(data);
                                    $('.city').html(data);
                                }
                });             
            $( "#member-sponser_id" ).change(function() {
                $sponser_id = 0;
                if(('#member-sponser_id')!=''){
                    $sponser_id  = $('#member-sponser_id').val();
                }
                        $.ajax({
                                type : 'post',
                                url : "<?= Url::to(['member/get-upline']);?>",
                                //dataType:"json",
                                data:{ 'sponser_id':$sponser_id},
                                success:function(data){ 
                                    $('#member-upline_id').val(data);
                                }
                        }); 

                        $.ajax({
                                type : 'post',
                                url : "<?= Url::to(['member/get-leg']);?>",
                                //dataType:"json",
                                data:{ 'sponser_id':$sponser_id},
                                success:function(data){ 
                                    $('#member-left_right_leg').html(data);
                                }
                        });                         
                    })
            // $( "#member-state" ).change(function() {

            //     $state_id = 0;
            //     if(('#member-state')!=''){
            //         $state_id  = $('#member-state').val();
            //     }
            //             $.ajax({
            //                     type : 'post',
            //                     url : "<?= Url::to(['member/get-state']);?>",
            //                     //dataType:"json",
            //                     data:{ 'state_id':$state_id},
            //                     success:function(data){ 
            //                         $('#member-city').html(data);
            //                     }
            //             });                        
            //         })            
        });
</script>

_protected/app/views/member/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\MemberSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="member-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'sponser_id') ?>

    <?= $form->field($model, 'upline_id') ?>

    <?= $form->field($model, 'left_right') ?>

    <?= $form->field($model, 'applicant_name') ?>

    <?php // echo $form->field($model, 'gender') ?>

    <?php // echo $form->field($model, 'name_type') ?>

    <?php // echo $form->field($model, 'father_spouse_name') ?>

    <?php // echo $form->field($model, 'dob') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'city') ?>

    <?php // echo $form->field($model, 'state') ?>

    <?php // echo $form->field($model, 'mobile') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'pan_no') ?>

    <?php // echo $form->field($model, 'aadhaar_no') ?>

    <?php // echo $form->field($model, 'bank_name') ?>

    <?php // echo $form->field($model, 'account_no') ?>

    <?php // echo $form->field($model, 'IFSC_code') ?>

    <?php // echo $form->field($model, 'account_holder_name') ?>

    <?php // echo $form->field($model, 'date') ?>

    <?php // echo $form->field($model, 'nomine_name') ?>

    <?php // echo $form->field($model, 'qualification') ?>

    <?php // echo $form->field($model, 'upload_photo') ?>

    <?php // echo $form->field($model, 'id_proof_photo') ?>

    <?php // echo $form->field($model, 'pan_card_photo') ?>

    <?php // echo $form->field($model, 'passbook_photo') ?>

    <?php // echo $form->field($model, 'password') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'created_on') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'updated_on') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

_protected/app/views/member/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Member */

$this->title = 'Create Member';
$this->params['breadcrumbs'][] = ['label' => 'Members', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card card-box">
    <div class="card-head">
    	<!-- <h3><?= Html::encode($this->title) ?></h3> -->
    </div>	
<div class="card-body">
    <?= $this->render('_form', [
        'model' => $model,
        'get_member_ddl' =>$get_member_ddl,
        'get_plan_ddl' =>$get_plan_ddl,
        'image'=>$image,
        'get_state_ddl' =>$get_state_ddl,
        
    ]) ?>
</div>
</div>

_protected/app/views/member/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\MemberSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Members';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card card-box">
    <div class="card-head">

    <!---<h1><?//= Html::encode($this->title) ?></h1>-->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Member', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
</div>
<div class="card-body">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'unique_id',
            'upline_id',
            //'left_right_leg',
            'applicant_name',
            //'gender',
            //'name_type',
            //'father_spouse_name',
            //'dob',
            //'address:ntext',
            //'city',
            //'state',
            //'mobile',
            //'email:email',
            //'pan_no',
            //'aadhaar_no',
            //'bank_name',
            //'account_no',
            //'IFSC_code',
            //'account_holder_name',
            //'date',
            //'nomine_name',
            //'qualification',
            //'password',
            //'created_by',
            //'created_on',
            //'updated_by',
            //'updated_on',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>
</div>

_protected/app/views/member/tree.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Member;
use yii\helpers\Url;
$this->title = 'Tree';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card card-box">
    <div class="card-head">
</div>
	<table class="table" align="center" border="0" style="text-align:center">
			<tr height="150">
					<td colspan="4"><a href="<?= Url::to(['member/view','id'=>$model->id]);?>" ><i class="fa fa-user fa-4x" style="color:#1430B1"></i><p><?= $model ? $model->applicant_name:'' ?></p></a></td>
					
			</tr>
			<tr height="150">
			<?php

				$left = New Member();
				$firstLeft = $left->getFindLeft($model->id);
				$firstRight = $left->getFindRight($model->id);

				//$secondLeft = $sLeft->getFindLeft($firstLeft->id);
				//$getfirstteamleft = Member::find()->where(['sponser_id'=>$model->id])->andWhere(['left_right_leg' => 'left'])->one();
				//$getfirstteamright = Member::find()->where(['sponser_id'=>$model->id])->andWhere(['left_right_leg' => 'right'])->one();
				//$getteam =$team->getFindteam($model->id);
				 //Member::getFindteam();
			?>
			<?php 
			if(!empty($firstLeft)){
			?>
			<td colspan="2"><a href="<?= Url::to(['member/view','id'=>$firstLeft->id]);?>"><i class="fa fa-user fa-4x" style="color:#D520BE"></i><p><?= $firstLeft->applicant_name;  ?></p></a></td>
			<?php 
			}
			else{
			?>
			<td colspan="2"><i class="fa fa-user fa-4x" style="color:#361515"></i><p><?php  ?></p></td>
			<?php
			}
			?>
			<?php 
			if(!empty($firstRight)){
			?>
			<td colspan="2"><a href="<?= Url::to(['member/view','id'=>$firstRight->id]);?>"><i class="fa fa-user fa-4x" style="color:#D520BE"></i><p><?= $firstRight->applicant_name;  ?></p></a></td>
			<?php 
			}
			else{
			?>
			<td colspan="2"><i class="fa fa-user fa-4x" style="color:#361515"></i><p><?php  ?></p></td>
			<?php
			}
		
			?>
			</tr>
			<tr height="150">
			<?php
				if($firstLeft->id !=false){
					$second = New Member();
					$secondLeft = $second->getFindLeft($firstLeft->id);
					$secondRight = $second->getFindRight($firstLeft->id);				
				}		
	

			if($firstRight->id !=false){
				$third = New Member();
					$thirdLeft = $third->getFindLeft($firstRight->id);
					$thirdRight = $third->getFindRight($firstRight->id);					
				}
							
				// $thirdteamleft = New Member();
				// $third_left = $getfirstteamleft['id'];
				// $thirdleftteam = Member::find()->where(['sponser_id'=>$third_left])->andWhere(['left_right_leg'=>'left'])->one();

				// $thirdrightteam = Member::find()->where(['sponser_id'=>$third_left])->andWhere(['left_right_leg'=>'right'])->one();

				// $getteamrightthird = Member::find()->where(['sponser_id'=>$getfirstteamright['id']])->andWhere(['left_right_leg'=>'right'])->one();
				// $getteamleftthird = Member::find()->where(['sponser_id'=>$getfirstteamright['id']])->andWhere(['left_right_leg'=>'left'])->one();

			?>
			<?php 
	
			if(isset($secondLeft) && $secondLeft !=false ){
			?>
			<td><a href="<?= Url::to(['member/view','id'=>$secondLeft->id]);?>"><i class="fa fa-user fa-4x" style="color:#D520BE"></i><p><?= $secondLeft->applicant_name;  ?></p></a></td>
			<?php 
			}
	
			else{
			?>
			<td><i class="fa fa-user fa-4x" style="color:#361515"></i></td>
			<?php
			}
			?>
			<?php 
						
			if(isset($secondRight) && $secondRight!=false){
			?>
			<td><a href="<?= Url::to(['member/view','id'=>$secondRight->id]);?>"><i class="fa fa-user fa-4x" style="color:#D520BE"></i><p><?= $secondRight->applicant_name;  ?></p></a></td>
			<?php 
			}
			
			else{
			?>
			<td><i class="fa fa-user fa-4x" style="color:#361515"></i></td>
			<?php
			}
			?>
			<?php 


			if($thirdLeft !=false && isset($thirdLeft)){
			?>
			<td><a href="<?= Url::to(['member/view','id'=>$thirdLeft->id]);?>"><i class="fa fa-user fa-4x" style="color:#D520BE"></i><p><?= $thirdLeft->applicant_name;  ?></p></a></td>
			<?php 
			}
		
			else{
			?>
			<td><i class="fa fa-user fa-4x" style="color:#361515"></i></td>
			<?php
			}
			?>
			<?php 
		
			if($thirdRight!=false && isset($thirdRight)){
			?>
			<td><a href="<?= Url::to(['member/view','id'=>$thirdRight->id]);?>"><i class="fa fa-user fa-4x" style="color:#D520BE"></i><p><?= $thirdRight->applicant_name;  ?></p></a></td>
			<?php 
			}
		
			else{
			?>
			<td><i class="fa fa-user fa-4x" style="color:#361515"></i></td>
			<?php
			}
			?>
			</tr>			
	</table>
</div>

_protected/app/views/member/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Member */

$this->title = 'Update Member: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Members', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="card card-box">
    <div class="card-head">

    <h1><?= Html::encode($this->title) ?></h1>
</div>
<div class="card-body">
    <?= $this->render('_update-form', [
        'model' => $model,
        'get_member_ddl' =>$get_member_ddl,
        'get_plan_ddl' =>$get_plan_ddl,
        'image'=>$image,  
        'get_state_ddl'=>$get_state_ddl,
        'get_city_ddl'=>$get_city_ddl,
    ]) ?>

</div>
</div>