_protected/app/controllers/RolePermissionController.php
<?php

namespace app\controllers;

use Yii;
use yii\helpers\ArrayHelper;
use common\models\Roles;
use common\models\Permission;
use common\models\RolePermission;
use common\models\PermissionGroup;
use common\models\RolePermissionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * RolePermissionController implements the CRUD actions for RolePermission model.
 */
class RolePermissionController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all RolePermission models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RolePermissionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single RolePermission model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new RolePermission model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new RolePermission();

        $getRole = Roles::find()
                        ->where(['status' => Roles::STATUS_ACTIVE])
                        ->all();

        $map_roles   =   ArrayHelper::map($getRole, 'id', 'name');

        $permGroup = PermissionGroup::find()
                                    ->where(['status' => PermissionGroup::STATUS_ACTIVE])
                                    ->all();

        $role = Yii::$app->request->get("role");
        $permission = null;
        if($role)
        {
            $permission = RolePermission::find()->select("permission_id")->where(['role_id' => $role])->all();
        }

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post())) {
            RolePermission::deleteAll(['role_id' => $role]);
            foreach (array_filter($model->permission_id) as $pK => $perm) {
                echo $perm;
                $new_model = new RolePermission();
                $new_model->permission_id   =   $perm;
                $new_model->role_id         =   $model->role_id;
                $new_model->status          =   $new_model::STATUS_ACTIVE;
                $new_model->created_by      =   Yii::$app->user->id;
                $new_model->save();
            }
            // return $this->redirect(['view', 'id' => $model->id]);
            return $this->refresh();
        }

        return $this->render('create', [
            'model' => $model,
            'map_roles' => $map_roles,
            'permGroup' => $permGroup,
            'permission' => $permission,
        ]);
    }

    /**
     * Updates an existing RolePermission model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing RolePermission model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the RolePermission model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return RolePermission the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = RolePermission::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

_protected/app/views/role-permission/_form.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\RolePermission */
/* @var $form yii\widgets\ActiveForm */
$model->role_id = Yii::$app->request->get("role");
?>

<div class="role-permission-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'role_id')->dropDownList($map_roles, ['class' => 'select-search', 'prompt' => 'Please Select', 'onchange' => "loadRole(this.value)"]) ?>
        </div>
    </div>

    <?php
    $perm_array = null;
    if($permission)
    {
        foreach ($permission as $perKey => $perm_val) {
            $perm_array[] = $perm_val->permission_id;
        }
    }

    foreach ($permGroup as $pKey => $group) {
        if($group->permission)
        {
        ?>
        <div class="row">
            <div class="col-md-12 m-b-20">
                <h5><u><?= $group->name; ?></u></h5>
                <div class="row">
                <?php
                    foreach($group->permission as $pKey => $permission) 
                    {
                        $data_checked = '';
                        if($perm_array)
                        {
                            if(in_array($permission->id, $perm_array))
                            {
                                $data_checked = "checked";
                            }
                        }
                    ?>
                        <div class="col-md-2">
                            <?= $form->field($model, 'permission_id[]')->checkbox(['label' => $permission->name, 'value' => $permission->id, 'data-checked' => $data_checked])->label(false) ?>
                            <?php $permission->name; ?>
                        </div>
                        <?php
                    }
                ?>
                </div>
            </div>
        </div>
        <hr />
        <?php
        }
    }
    ?>
    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script type="text/javascript">
    function loadRole(value)
    {
        window.location = "<?= Url::to(['role-permission/create', "role" => '']); ?>"+value;
    }
</script>

<?php
$loadJs = '
    $(document).ready(function(){
        $checked = $(this).find("input").each(function(){
            $is_checked = $(this).attr("data-checked");
            if($is_checked == "checked")
            {
            // console.log($is_checked);
                $(this).prop("checked", true);
            }
        });
    });
';

$this->registerJs($loadJs);
?>

_protected/app/views/role-permission/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\RolePermissionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="role-permission-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'permission_id') ?>

    <?= $form->field($model, 'role_id') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'created_on') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'updated_on') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

_protected/app/views/role-permission/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\RolePermission */

$this->title = Yii::t('app', 'Create Role Permission');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Role Permissions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="card card-box">
    <div class="card-head">
    	<header><?= Html::encode($this->title) ?></header>
    </div>
    <div class="card-body " id="bar-parent">
	    <?= $this->render('_form', [
	        'model' => $model,
	        'map_roles' => $map_roles,
            'permGroup' => $permGroup,
            'permission' => $permission,
	    ]) ?>
	</div>
</div>

_protected/app/views/role-permission/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\RolePermissionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Role Permissions');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card card-box">
    <div class="card-body " id="bar-parent">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Role Permission'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'permission_id',
            'role_id',
            'status',
            'created_by',
            //'created_on',
            //'updated_by',
            //'updated_on',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
    </div>
</div>

_protected/app/views/role-permission/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\RolePermission */

$this->title = Yii::t('app', 'Update Role Permission: {nameAttribute}', [
    'nameAttribute' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Role Permissions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>

<div class="card card-box">
    <div class="card-head">
    	<header><?= Html::encode($this->title) ?></header>
    </div>
    <div class="card-body " id="bar-parent">
	    <?= $this->render('_form', [
	        'model' => $model,
	    ]) ?>
	</div>
</div>

_protected/app/views/role-permission/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\RolePermission */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Role Permissions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="role-permission-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'permission_id',
            'role_id',
            'status',
            'created_by',
            'created_on',
            'updated_by',
            'updated_on',
        ],
    ]) ?>

</div>